import {ClipboardList ,ChartColumn,UtensilsCrossed , Home, NotepadText, Package, PackagePlus, Settings, ShoppingBag, UserCheck, UserPlus, Users } from "lucide-react";

import ProfileImage from "@/assets/profile-image.jpg";
import ProductImage from "@/assets/product-image.jpg";

export const navbarLinks = [
    {
        title: "Slide Bar",
        links: [
            {
                label: "Dashboard",
                icon: Home,
                path: "/",
            },
            {
                label: "FoodItem",
                icon: UtensilsCrossed ,
                path: "/FoodItem",
            },
            {
                label: "Pending Orders",
                icon: ClipboardList,
                path: "/PendingOrders",
            },
            {
                label: "Confirm Orders",
                icon: ClipboardList,
                path: "/ConfirmOrders",
            },
            {
                label: "Delivered Orders",
                icon: ClipboardList,
                path: "/DeliveredOrders",
            },
        ],
    },
    // {
    //     title: "Customers",
    //     links: [
    //         {
    //             label: "Customers",
    //             icon: Users,
    //             path: "/customers",
    //         },
    //         {
    //             label: "New customer",
    //             icon: UserPlus,
    //             path: "/new-customer",
    //         },
    //         {
    //             label: "Verified customers",
    //             icon: UserCheck,
    //             path: "/verified-customers",
    //         },
    //     ],
    // },
    // {
    //     title: "Products",
    //     links: [
    //         {
    //             label: "Products",
    //             icon: Package,
    //             path: "/products",
    //         },
    //         {
    //             label: "New product",
    //             icon: PackagePlus,
    //             path: "/new-product",
    //         },
    //         {
    //             label: "Inventory",
    //             icon: ShoppingBag,
    //             path: "/inventory",
    //         },
    //     ],
    // },
    // {
    //     title: "Settings",
    //     links: [
    //         {
    //             label: "Settings",
    //             icon: Settings,
    //             path: "/settings",
    //         },
    //     ],
    // },
];

export const overviewData = [
    {
        name: "Jan",
        total: 1500,
    },
    {
        name: "Feb",
        total: 2000,
    },
    {
        name: "Mar",
        total: 1000,
    },
    {
        name: "Apr",
        total: 5000,
    },
    {
        name: "May",
        total: 2000,
    },
    {
        name: "Jun",
        total: 5900,
    },
    {
        name: "Jul",
        total: 2000,
    },
    {
        name: "Aug",
        total: 5500,
    },
    {
        name: "Sep",
        total: 2000,
    },
    {
        name: "Oct",
        total: 4000,
    },
    {
        name: "Nov",
        total: 1500,
    },
    {
        name: "Dec",
        total: 2500,
    },
];

export const recentSalesData = [
    {
        id: 1,
        name: "Olivia Martin",
        email: "olivia.martin@email.com",
        image: ProfileImage,
        total: 1500,
    },
    {
        id: 2,
        name: "James Smith",
        email: "james.smith@email.com",
        image: ProfileImage,
        total: 2000,
    },
    {
        id: 3,
        name: "Sophia Brown",
        email: "sophia.brown@email.com",
        image: ProfileImage,
        total: 4000,
    },
    {
        id: 4,
        name: "Noah Wilson",
        email: "noah.wilson@email.com",
        image: ProfileImage,
        total: 3000,
    },
    {
        id: 5,
        name: "Emma Jones",
        email: "emma.jones@email.com",
        image: ProfileImage,
        total: 2500,
    },
    {
        id: 6,
        name: "William Taylor",
        email: "william.taylor@email.com",
        image: ProfileImage,
        total: 4500,
    },
    {
        id: 7,
        name: "Isabella Johnson",
        email: "isabella.johnson@email.com",
        image: ProfileImage,
        total: 5300,
    },
];

export const topProducts = [
    {
        number: 1,
        name: "Wireless Headphones",
        image: ProductImage,
        description: "High-quality noise-canceling wireless headphones.",
        price: 99.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 2,
        name: "Smartphone",
        image: ProductImage,
        description: "Latest 5G smartphone with excellent camera features.",
        price: 799.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 3,
        name: "Gaming Laptop",
        image: ProductImage,
        description: "Powerful gaming laptop with high-end graphics.",
        price: 1299.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 4,
        name: "Smartwatch",
        image: ProductImage,
        description: "Stylish smartwatch with fitness tracking features.",
        price: 199.99,
        status: "Out of Stock",
        rating: 4.4,
    },
    {
        number: 5,
        name: "Bluetooth Speaker",
        image: ProductImage,
        description: "Portable Bluetooth speaker with deep bass sound.",
        price: 59.99,
        status: "In Stock",
        rating: 4.3,
    },
    {
        number: 6,
        name: "4K Monitor",
        image: ProductImage,
        description: "Ultra HD 4K monitor with stunning color accuracy.",
        price: 399.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 7,
        name: "Mechanical Keyboard",
        image: ProductImage,
        description: "Mechanical keyboard with customizable RGB lighting.",
        price: 89.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 8,
        name: "Wireless Mouse",
        image: ProductImage,
        description: "Ergonomic wireless mouse with precision tracking.",
        price: 49.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 9,
        name: "Action Camera",
        image: ProductImage,
        description: "Waterproof action camera with 4K video recording.",
        price: 249.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 10,
        name: "External Hard Drive",
        image: ProductImage,
        description: "Portable 2TB external hard drive for data storage.",
        price: 79.99,
        status: "Out of Stock",
        rating: 4.5,
    },
    {
        number: 11,
        name: "Noise-Canceling Earbuds",
        image: ProductImage,
        description: "Compact earbuds with excellent sound and noise-canceling features.",
        price: 89.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 12,
        name: "Portable Power Bank",
        image: ProductImage,
        description: "High-capacity portable power bank for on-the-go charging.",
        price: 29.99,
        status: "In Stock",
        rating: 4.4,
    },
    {
        number: 13,
        name: "Smart Home Hub",
        image: ProductImage,
        description: "Centralized smart home controller with voice assistant integration.",
        price: 149.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 14,
        name: "Gaming Headset",
        image: ProductImage,
        description: "High-quality gaming headset with surround sound and microphone.",
        price: 129.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 15,
        name: "4K Streaming Stick",
        image: ProductImage,
        description: "Plug-in streaming device for 4K content.",
        price: 49.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 16,
        name: "Robot Vacuum Cleaner",
        image: ProductImage,
        description: "Smart robot vacuum with Wi-Fi connectivity and scheduling.",
        price: 199.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 17,
        name: "Bluetooth Earphones",
        image: ProductImage,
        description: "Lightweight Bluetooth earphones with a comfortable fit.",
        price: 39.99,
        status: "In Stock",
        rating: 4.3,
    },
    {
        number: 18,
        name: "Electric Toothbrush",
        image: ProductImage,
        description: "Advanced electric toothbrush with multiple cleaning modes.",
        price: 89.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 19,
        name: "Smart Thermostat",
        image: ProductImage,
        description: "Wi-Fi-enabled thermostat for energy-efficient home temperature control.",
        price: 149.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 20,
        name: "Smart Light Bulbs",
        image: ProductImage,
        description: "Color-changing smart light bulbs with app and voice control.",
        price: 29.99,
        status: "In Stock",
        rating: 4.4,
    },
    {
        number: 21,
        name: "Electric Kettle",
        image: ProductImage,
        description: "Fast boiling electric kettle with auto shut-off feature.",
        price: 39.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 22,
        name: "Smart Security Camera",
        image: ProductImage,
        description: "Wireless security camera with night vision and motion detection.",
        price: 119.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 23,
        name: "Smart Plugs",
        image: ProductImage,
        description: "Wi-Fi-enabled plugs for smart home automation.",
        price: 24.99,
        status: "In Stock",
        rating: 4.4,
    },
    {
        number: 24,
        name: "Digital Camera",
        image: ProductImage,
        description: "Compact digital camera with HD video recording.",
        price: 199.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 25,
        name: "Smart Light Switch",
        image: ProductImage,
        description: "Voice-controlled smart light switch for home automation.",
        price: 49.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 26,
        name: "Wireless Charging Pad",
        image: ProductImage,
        description: "Fast wireless charging pad for smartphones and other devices.",
        price: 29.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 27,
        name: "Electric Grill",
        image: ProductImage,
        description: "Compact electric grill for indoor grilling.",
        price: 79.99,
        status: "In Stock",
        rating: 4.3,
    },
    {
        number: 28,
        name: "Home Theater System",
        image: ProductImage,
        description: "Surround sound home theater system with subwoofer.",
        price: 399.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 29,
        name: "Fitness Tracker",
        image: ProductImage,
        description: "Wearable fitness tracker with heart rate monitoring.",
        price: 79.99,
        status: "In Stock",
        rating: 4.5,
    },
    {
        number: 30,
        name: "Smart Door Lock",
        image: ProductImage,
        description: "Keyless entry smart door lock with remote control.",
        price: 149.99,
        status: "In Stock",
        rating: 4.7,
    },
    {
        number: 31,
        name: "Electric Bike",
        image: ProductImage,
        description: "Eco-friendly electric bike for efficient commuting.",
        price: 799.99,
        status: "In Stock",
        rating: 4.8,
    },
    {
        number: 32,
        name: "Wireless Security System",
        image: ProductImage,
        description: "Comprehensive wireless security system with app control.",
        price: 299.99,
        status: "In Stock",
        rating: 4.6,
    },
    {
        number: 33,
        name: "Smart Water Bottle",
        image: ProductImage,
        description: "Smart water bottle that tracks hydration levels.",
        price: 49.99,
        status: "In Stock",
        rating: 4.4,
    },
    {
        number: 34,
        name: "Portable Air Conditioner",
        image: ProductImage,
        description: "Compact portable air conditioner for small rooms.",
        price: 229.99,
        status: "In Stock",
        rating: 4.5,
    }
    
];
